
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shari
 */
public class POS extends javax.swing.JFrame {

    /**
     * Creates new form POS
     */
    public POS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
//    FUNCTION COST
    public void ItemCost() {
        double sum = 0;
        
        for (int i=0; i<jTable1.getRowCount(); i++) {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        jtxtSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
        
        double cTax = (cTotal1 * 3.9)/100;
        String iTaxTotal = String.format("Ksh %.2f", cTax);
        jtxtTax.setText(iTaxTotal);
        
        String iSubTotal = String.format("Ksh %.2f", cTotal1);
        jtxtSubTotal.setText(iSubTotal);
        
        String iTotal = String.format("Ksh %.2f", cTotal1 + cTax);
        jtxtTotal.setText(iTotal);
        
        String BarCode = String.format("Total is Ksh %.2f", cTotal1 + cTax);
        jtxtBarCode.setText(BarCode);
          
    }
    
//    FUNCTION CHANGE
    public void Change() {
        double sum = 0;
        double tax = 3.9;
        double cash = Double.parseDouble(jtxtDisplay.getText());
        
        for (int i=0; i < jTable1.getRowCount(); i++){
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        double cTax = (sum * tax)/100;
        double cChange = (cash - (sum + cTax));
        
        String ChangeGiven = String.format("Ksh %.2f", cChange);
        jtxtChange.setText(ChangeGiven);
        
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnVeggiePizza = new javax.swing.JButton();
        jbtnFrenchToast = new javax.swing.JButton();
        jbtnSaladBowl = new javax.swing.JButton();
        jbtnSalmon = new javax.swing.JButton();
        jbtnGrilledSandwich = new javax.swing.JButton();
        jbtnSandwich = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jbtnKachumbari = new javax.swing.JButton();
        jbtnPoachedEggs = new javax.swing.JButton();
        jbtnOrangeJuice = new javax.swing.JButton();
        jbtnBurger = new javax.swing.JButton();
        jbtnRiceBowl = new javax.swing.JButton();
        jbtnPumpkinSoup = new javax.swing.JButton();
        jbtnSoufflePancake = new javax.swing.JButton();
        jbtnVegetableSoup = new javax.swing.JButton();
        jbtnRamen = new javax.swing.JButton();
        jbtnPestoPasta = new javax.swing.JButton();
        jbtnTurkishEggs = new javax.swing.JButton();
        jbtnOatmeal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtChange = new javax.swing.JTextField();
        jtxtDisplay = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jtxtBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnVeggiePizza.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnVeggiePizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/anna-pelzer-iecg0mWrnlE-unsplash.jpg"))); // NOI18N
        jbtnVeggiePizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVeggiePizzaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnVeggiePizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 100, 90));

        jbtnFrenchToast.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnFrenchToast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/anh-nguyen-fdXnVBurIvU-unsplash.jpg"))); // NOI18N
        jbtnFrenchToast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFrenchToastActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnFrenchToast, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 90));

        jbtnSaladBowl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnSaladBowl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/anna-pelzer-IGfIGP5ONV0-unsplash (1).jpg"))); // NOI18N
        jbtnSaladBowl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaladBowlActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSaladBowl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 90));

        jbtnSalmon.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnSalmon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/caroline-attwood-bpPTlXWTOvg-unsplash.jpg"))); // NOI18N
        jbtnSalmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalmonActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSalmon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 100, 90));

        jbtnGrilledSandwich.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnGrilledSandwich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chad-montano-MqT0asuoIcU-unsplash (1).jpg"))); // NOI18N
        jbtnGrilledSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGrilledSandwichActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGrilledSandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 100, 90));

        jbtnSandwich.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnSandwich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eiliv-sonas-aceron-mAQZ3X_8_l0-unsplash.jpg"))); // NOI18N
        jbtnSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSandwichActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 100, 90));

        jButton27.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jPanel1.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 90));

        jButton28.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jPanel1.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 90));

        jButton29.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jPanel1.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 100, 90));

        jButton37.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jPanel1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 100, 90));

        jButton38.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jPanel1.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 100, 90));

        jButton39.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jPanel1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 100, 90));

        jbtnKachumbari.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnKachumbari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/khloe-arledge--Uca3SGlOag-unsplash.jpg"))); // NOI18N
        jbtnKachumbari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKachumbariActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnKachumbari, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 90));

        jbtnPoachedEggs.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnPoachedEggs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/olesia-buyar-zaiEh-8mznM-unsplash.jpg"))); // NOI18N
        jbtnPoachedEggs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPoachedEggsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPoachedEggs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 100, 90));

        jbtnOrangeJuice.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnOrangeJuice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/no-revisions-gA81ZTsql68-unsplash (1).jpg"))); // NOI18N
        jbtnOrangeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOrangeJuiceActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnOrangeJuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 100, 90));

        jbtnBurger.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mike-PxJ9zkM2wdA-unsplash.jpg"))); // NOI18N
        jbtnBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBurgerActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 100, 90));

        jbtnRiceBowl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnRiceBowl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eiliv-sonas-aceron-ZuIDLSz3XLg-unsplash (1).jpg"))); // NOI18N
        jbtnRiceBowl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRiceBowlActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRiceBowl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 100, 90));

        jbtnPumpkinSoup.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnPumpkinSoup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cala-w6ftFbPCs9I-unsplash.jpg"))); // NOI18N
        jbtnPumpkinSoup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPumpkinSoupActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPumpkinSoup, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 100, 90));

        jbtnSoufflePancake.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnSoufflePancake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/joseph-gonzalez-zcUgjyqEwe8-unsplash.jpg"))); // NOI18N
        jbtnSoufflePancake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSoufflePancakeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSoufflePancake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, 90));

        jbtnVegetableSoup.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnVegetableSoup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/khloe-arledge-ND3edEmzcdQ-unsplash.jpg"))); // NOI18N
        jbtnVegetableSoup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVegetableSoupActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnVegetableSoup, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 100, 90));

        jbtnRamen.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnRamen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mgg-vitchakorn-98Xi5vMGKck-unsplash.jpg"))); // NOI18N
        jbtnRamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRamenActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 100, 90));

        jbtnPestoPasta.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnPestoPasta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mgg-vitchakorn-PLyJqEJVre0-unsplash.jpg"))); // NOI18N
        jbtnPestoPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPestoPastaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPestoPasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 100, 90));

        jbtnTurkishEggs.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnTurkishEggs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/do-mee-SH8_JmrsQcw-unsplash.jpg"))); // NOI18N
        jbtnTurkishEggs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTurkishEggsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnTurkishEggs, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 100, 90));

        jbtnOatmeal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnOatmeal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/joseph-gonzalez-Wns3U-oVoLA-unsplash.jpg"))); // NOI18N
        jbtnOatmeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOatmealActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnOatmeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 100, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 720, 350));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 70, 60));

        jbtn7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 60));

        jbtn8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 70, 60));

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton8.setText("7");
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 60));

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton9.setText("7");
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 70, 60));

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton10.setText("7");
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 70, 60));

        jbtn4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 60));

        jbtn6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 70, 60));

        jbtn5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 70, 60));

        jbtn1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 60));

        jbtn3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 70, 60));

        jbtn2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 70, 60));

        jButton17.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton17.setText("7");
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 60));

        jButton18.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton18.setText("7");
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 70, 60));

        jButton19.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton19.setText("7");
        jPanel2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 70, 60));

        jbtn0.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, 60));

        jbtnC.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 70, 60));

        jbtnDot.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 70, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 280, 350));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 270, 270));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Total : ");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("SubTotal : ");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Tax : ");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 180, 30));

        jtxtSubTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 180, 30));

        jtxtTax.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel5.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 160));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 150));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnExit.setText("EXIT");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 140, 50));

        jbtnPay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 50));

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 50));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 140, 50));

        jbtnRemove.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 140, 50));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 390, 170));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Payment Method ");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Cash : ");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Change :");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jtxtChange.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel8.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 180, 30));

        jtxtDisplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        jPanel8.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 180, 30));

        jcboPayment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "M-Pesa", "Card", " " }));
        jPanel8.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 11, 180, 30));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 400, 160));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 1330, 200));

        jtxtBarCode.setFont(new java.awt.Font("C39HrP24DlTt", 0, 24)); // NOI18N
        jtxtBarCode.setText("ghfg");
        jtxtBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBarCodeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 270, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jtxtBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBarCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBarCodeActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
        String enterNumber = jtxtDisplay.getText();
       
       if (enterNumber == "") {
           jtxtDisplay.setText(jbtn8.getText());
       } else {
           enterNumber = jtxtDisplay.getText() + jbtn8.getText();
           jtxtDisplay.setText(enterNumber);
       }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
       String enterNumber = jtxtDisplay.getText();
       
       if (enterNumber == "") {
           jtxtDisplay.setText(jbtn7.getText());
       } else {
           enterNumber = jtxtDisplay.getText() + jbtn7.getText();
           jtxtDisplay.setText(enterNumber);
       }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
String enterNumber = jtxtDisplay.getText();
       
       if (enterNumber == "") {
           jtxtDisplay.setText(jbtn9.getText());
       } else {
           enterNumber = jtxtDisplay.getText() + jbtn9.getText();
           jtxtDisplay.setText(enterNumber);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String enterNumber = jtxtDisplay.getText();
       
       if (enterNumber == "") {
           jtxtDisplay.setText(jbtn4.getText());
       } else {
           enterNumber = jtxtDisplay.getText() + jbtn4.getText();
           jtxtDisplay.setText(enterNumber);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
       String enterNumber = jtxtDisplay.getText();
       
       if (enterNumber == "") {
           jtxtDisplay.setText(jbtn5.getText());
       } else {
           enterNumber = jtxtDisplay.getText() + jbtn5.getText();
           jtxtDisplay.setText(enterNumber);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String enterNumber = jtxtDisplay.getText();
       
       if (enterNumber == "") {
           jtxtDisplay.setText(jbtn6.getText());
       } else {
           enterNumber = jtxtDisplay.getText() + jbtn6.getText();
           jtxtDisplay.setText(enterNumber);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String enterNumber = jtxtDisplay.getText();
       
       if (enterNumber == "") {
           jtxtDisplay.setText(jbtn1.getText());
       } else {
           enterNumber = jtxtDisplay.getText() + jbtn1.getText();
           jtxtDisplay.setText(enterNumber);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        String enterNumber = jtxtDisplay.getText();
       
       if (enterNumber == "") {
           jtxtDisplay.setText(jbtn2.getText());
       } else {
           enterNumber = jtxtDisplay.getText() + jbtn2.getText();
           jtxtDisplay.setText(enterNumber);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String enterNumber = jtxtDisplay.getText();
       
       if (enterNumber == "") {
           jtxtDisplay.setText(jbtn3.getText());
       } else {
           enterNumber = jtxtDisplay.getText() + jbtn3.getText();
           jtxtDisplay.setText(enterNumber);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        String enterNumber = jtxtDisplay.getText();
       
       if (enterNumber == "") {
           jtxtDisplay.setText(jbtn0.getText());
       } else {
           enterNumber = jtxtDisplay.getText() + jbtn0.getText();
           jtxtDisplay.setText(enterNumber);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        if (! jtxtDisplay.getText().contains(".")) {
            jtxtDisplay.setText(jtxtDisplay.getText() + jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
            jtxtDisplay.setText("");
            jtxtChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnFrenchToastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFrenchToastActionPerformed
        double PriceOfItem = 150;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"French Toast", "1", PriceOfItem});
        ItemCost();
        
    }//GEN-LAST:event_jbtnFrenchToastActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jbtnOrangeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOrangeJuiceActionPerformed
   
        double PriceOfItem = 100;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Orange Juice", "1", PriceOfItem});
        ItemCost();// TODO add your handling code here:
    }//GEN-LAST:event_jbtnOrangeJuiceActionPerformed

    private void jbtnSaladBowlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaladBowlActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 250;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Salad Bowl", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnSaladBowlActionPerformed

    private void jbtnVeggiePizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVeggiePizzaActionPerformed
            // TODO add your handling code here:
        double PriceOfItem = 550;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Veggie Pizza", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnVeggiePizzaActionPerformed

    private void jbtnSalmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalmonActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 400;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Baked Salmon", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnSalmonActionPerformed

    private void jbtnGrilledSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGrilledSandwichActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 450;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Grilled Sandwich", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnGrilledSandwichActionPerformed

    private void jbtnSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSandwichActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 300;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Tuna Sandwich", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnSandwichActionPerformed

    private void jbtnKachumbariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKachumbariActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 100;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Kachumbari", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnKachumbariActionPerformed

    private void jbtnPoachedEggsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPoachedEggsActionPerformed
        double PriceOfItem = 80;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Poached Eggs", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnPoachedEggsActionPerformed

    private void jbtnBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBurgerActionPerformed
        double PriceOfItem = 250;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Burger", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnBurgerActionPerformed

    private void jbtnRiceBowlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRiceBowlActionPerformed
        double PriceOfItem = 310;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Rice Bowl", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnRiceBowlActionPerformed

    private void jbtnPumpkinSoupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPumpkinSoupActionPerformed
        double PriceOfItem = 240;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Pumpkin Soup", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnPumpkinSoupActionPerformed

    private void jbtnSoufflePancakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSoufflePancakeActionPerformed
        double PriceOfItem = 180;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Soufle Pancake", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnSoufflePancakeActionPerformed

    private void jbtnVegetableSoupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVegetableSoupActionPerformed
        double PriceOfItem = 280;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chicken Soup", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnVegetableSoupActionPerformed

    private void jbtnRamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRamenActionPerformed
       double PriceOfItem = 320;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ramen Bowl", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnRamenActionPerformed

    private void jbtnPestoPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPestoPastaActionPerformed
        double PriceOfItem = 400;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Pesto Pasta", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnPestoPastaActionPerformed

    private void jbtnTurkishEggsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTurkishEggsActionPerformed
        double PriceOfItem = 180;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Turkish Eggs", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnTurkishEggsActionPerformed

    private void jbtnOatmealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOatmealActionPerformed
         double PriceOfItem = 120;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Oatmeal", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnOatmealActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        if (jcboPayment.getSelectedItem().equals("Cash")) {
            Change();
        } else {
            jtxtChange.setText("");
            jtxtDisplay.setText("");
        }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarCode.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        
        MessageFormat header = new MessageFormat("Printing in Progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integerProgress}");
        
        try 
        {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        } 
        catch (java.awt.print.PrinterException e) 
        {
            System.err.format("No Printer Found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int RemoveItem = jTable1.getSelectedRow();
        if (RemoveItem >= 0) {
            model.removeRow(RemoveItem);
        }
        
        ItemCost();
        
        if (jcboPayment.getSelectedItem().equals("Cash")) {
            Change();
        } else {
            jtxtChange.setText("");
            jtxtDisplay.setText("");
        }
                
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private JFrame frame; 
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to eixt", "Point of Sale",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBurger;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnFrenchToast;
    private javax.swing.JButton jbtnGrilledSandwich;
    private javax.swing.JButton jbtnKachumbari;
    private javax.swing.JButton jbtnOatmeal;
    private javax.swing.JButton jbtnOrangeJuice;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPestoPasta;
    private javax.swing.JButton jbtnPoachedEggs;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnPumpkinSoup;
    private javax.swing.JButton jbtnRamen;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnRiceBowl;
    private javax.swing.JButton jbtnSaladBowl;
    private javax.swing.JButton jbtnSalmon;
    private javax.swing.JButton jbtnSandwich;
    private javax.swing.JButton jbtnSoufflePancake;
    private javax.swing.JButton jbtnTurkishEggs;
    private javax.swing.JButton jbtnVegetableSoup;
    private javax.swing.JButton jbtnVeggiePizza;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
